main: cosmo.betterminecraft.Core
name: BetterMinecraft
version: 1.0.0
api-version: 1.16
description: Makes minecraft better, just believe me!
author: Vento
commands:
  #  killtest:
  #    name: killtest
  #    description: sets health to 0
  gethealth:
    name: gethealth
    description: prints your health
  ic:
    name: ic
    description: Gives a custom item if exists
  balance:
    name: balance
    description: gets your balance
  moneygui:
    name: moneygui
    description: opens the money gui